# Basic
title: Memory Pocket
subtitle: 
welcome_message: 
description: Ideas, Conversations, Stuff, Life.
creator: Afra L.

url: https://afralst.github.io/              # your host, for absolute URL
#baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

#blog_button:
#    title: Home | 主頁
#    description: Home

nav:
    - {title: ABOUT | 關於, description: ABOUT, url: /about}

    - {title: ARCHIVE | 編年, description: ARCHIVE, url: /archive}
    
    - {title: KEYWORDS | 搜尋, description: KEYWORDS, url: /tags}

# Pagination
plugins: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: username
    # duoshuo:
# Social
social:
    # weibo: username
    # github: username
    # twitter: username
    # gplus: username
    # mail: afra.liust@gmail.com

# Google Analytics
ga:
   # id: UA-xxxxxxxx-x
   # host: xxxxx.com
