# Basic
title: Afra's
subtitle: 上善若水，人淡如菊
welcome_message: 可以用html超文本code编辑格式?
description: My Memory Pocket
creator: 可以用html超文本code编辑格式?

url: https://afralst.github.io/OneV/

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

blog_button:
    title: Home
    description: Home

nav:
    - {title: AA1, description: AA1-DES, url: /TAGS}
    - {title: AA2, description: AA2-DES, url: /ARCHIVE}
    - {title: AA3, description: AA3-DES, url: '/ABOUT}

# Pagination
plugins: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: username
    # duoshuo:
# Social
social:
    # weibo: username
    # github: username
    # twitter: username
    # gplus: username
    # mail: afra.liust@gmail.com

# Google Analytics
ga:
   # id: UA-xxxxxxxx-x
   # host: xxxxx.com
